### ISSUE TITLE
Should we just make the logos downloadable straight from readme?

### ISSUE THREAD

**Issue by AidarItkulov** [gnolang/branding#4]
It seems like file manager is not gonna be the most convenient way to download things for non-tech folks. What do you think?

**Comment by moul** [comment]
Please review PR #5.

This PR introduces functionality to download the entire repository as a zip file. However, I have a couple of recommendations to improve the structure and user experience:

1. Consider removing any `.DS_Store` files for cleanliness.
2. Simplify the directory structure. Instead of a path like `assets/icon/dark/pdf.pdf`, opt for `assets/icon-dark.pdf`. This way, when users explore the root folder, they'll instantly see all available resources in every format.
